[project]
name = "school-code-env"
version = "0.1.0"
description = "Simple python codes used for chemical engineering courses"
readme = "README.md"
authors = [
    { name = "sebkaul", email = "sebkaul@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scipy>=1.18.1",
]

[project.scripts]
school-code-env = "school_code_env:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
