[project]
name = "school-code-env"
version = "0.1.0"
description = "Simple python codes used for chemical engineering courses"
readme = "README.md"
authors = [
    { name = "sebkaul", email = "sebkaul@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyqt6>=6.11.0",
    "scipy>=1.18.1",
]

[project.scripts]
school-code-env = "school_code_env:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.9",
]

[tool.pylint.messages_control]
disable = [
 "C",                    # conventions: naming, docstrings, whitespace, line length
 "R",                    # refactor suggestions
 "redefined-outer-name", # same variable name inside and outside a function
 "unused-variable",      # unused variables
]
