[project]
name = "school-code-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sebkaul", email = "sebkaul@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
school-code-env = "school_code_env:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
